server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:7800/ecommerce
    user: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  hibernate:
    ddl_auto: update
  show-sql: true
